version: "3"

services:
#  mariadb:
#    image: mariadb
#    environment:
#      MYSQL_ROOT_PASSWORD: secret-pw
#      MYSQL_DATABASE: moodle
#      MYSQL_USER: moodle
#      MYSQL_PASSWORD: moodle
##      command: --default-character-set=utf8mb4 --innodb_file_format=Barracuda --innodb_file_per_table=1 --innodb_large_prefix --character-set-client-handshake=FALSE --character-set-server=utf8mb4 --collation_server=utf8mb4_unicode_ci --default-character-set=utf8mb4
#      command: --default-character-set=utf8mb4 --innodb_file_format=Barracuda --innodb_file_per_table=1 --innodb_large_prefix --character-set-client-handshake=FALSE --character-set-server=utf8mb4 --collation_server=utf8mb4_unicode_ci --default-character-set=utf8mb4
##    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # The simple way to override the mariadb config.
#    volumes:
#      - mysql:/var/lib/mysql
#      - ./mysql/config:/etc/mysql/conf.d
##      - ./docker-runtime/mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#    ports:
#      - "3000:3306"
#    networks:
#      - code-network

  postgres:
    image: postgres:9.6.3
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: moodle
      POSTGRES_DB: moodle
    ports:
      - "5432:5432"
      # exposes 5432
    networks:
      - code-network


  php:
#    build: ./dockerphp
    build: ./dockerphp # Moodle 3.3 development release
#    build: ./dockerphp/moodle27 # Moodle 2.7 stable
    volumes:
      - moodledata:/var/www/moodledata
      - ./moodleupload:/moodleupload
      - moodle:/var/www/html
      - ./configs/php/php.ini:/usr/local/etc/php/php.ini
#      Comment out for fresh install
      - ./moodleconfig/config.php:/var/www/html/config.php
      - ./mod/hvp:/var/www/html/mod/hvp
#      Comment in to add custom theme
#      - ./themes/h5pmods-moodle-plugin:/var/www/html/theme/h5pmod
#      Comment in to test moodle code quality tools
#      - ./codechecker/moodle-plugin-ci:/var/www/mpc/
    networks:
      - code-network

  nginx:
    build: ./nginx
    depends_on:
      - php
    volumes:
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
# From php
      - moodledata:/var/www/moodledata
      - ./moodleupload:/moodleupload
      - moodle:/var/www/html
      - ./moodleconfig/config.php:/var/www/html/config.php
      - ./mod/hvp:/var/www/html/mod/hvp
#      - ./themes/h5pmods-moodle-plugin:/var/www/html/theme/h5pmod
    ports:
      - "80:80"
    networks:
      - code-network

volumes:
  mysql:
  moodle:
  moodledata:

networks:
  code-network:
    driver: bridge
